// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	identity "github.com/gcollin65/barbershop/internal/identity"
	mock "github.com/stretchr/testify/mock"
)

// MockMembershipRepository is an autogenerated mock type for the MembershipRepository type
type MockMembershipRepository struct {
	mock.Mock
}

type MockMembershipRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMembershipRepository) EXPECT() *MockMembershipRepository_Expecter {
	return &MockMembershipRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, m
func (_m *MockMembershipRepository) Create(ctx context.Context, m identity.Membership) (identity.Membership, error) {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 identity.Membership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identity.Membership) (identity.Membership, error)); ok {
		return rf(ctx, m)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identity.Membership) identity.Membership); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Get(0).(identity.Membership)
	}

	if rf, ok := ret.Get(1).(func(context.Context, identity.Membership) error); ok {
		r1 = rf(ctx, m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMembershipRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMembershipRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - m identity.Membership
func (_e *MockMembershipRepository_Expecter) Create(ctx interface{}, m interface{}) *MockMembershipRepository_Create_Call {
	return &MockMembershipRepository_Create_Call{Call: _e.mock.On("Create", ctx, m)}
}

func (_c *MockMembershipRepository_Create_Call) Run(run func(ctx context.Context, m identity.Membership)) *MockMembershipRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identity.Membership))
	})
	return _c
}

func (_c *MockMembershipRepository_Create_Call) Return(_a0 identity.Membership, _a1 error) *MockMembershipRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMembershipRepository_Create_Call) RunAndReturn(run func(context.Context, identity.Membership) (identity.Membership, error)) *MockMembershipRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, shopID, userID
func (_m *MockMembershipRepository) Delete(ctx context.Context, shopID string, userID string) error {
	ret := _m.Called(ctx, shopID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, shopID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMembershipRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMembershipRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID string
//   - userID string
func (_e *MockMembershipRepository_Expecter) Delete(ctx interface{}, shopID interface{}, userID interface{}) *MockMembershipRepository_Delete_Call {
	return &MockMembershipRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, shopID, userID)}
}

func (_c *MockMembershipRepository_Delete_Call) Run(run func(ctx context.Context, shopID string, userID string)) *MockMembershipRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMembershipRepository_Delete_Call) Return(_a0 error) *MockMembershipRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMembershipRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMembershipRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByShopAndUser provides a mock function with given fields: ctx, shopID, userID
func (_m *MockMembershipRepository) GetByShopAndUser(ctx context.Context, shopID string, userID string) (identity.Membership, error) {
	ret := _m.Called(ctx, shopID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByShopAndUser")
	}

	var r0 identity.Membership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (identity.Membership, error)); ok {
		return rf(ctx, shopID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) identity.Membership); ok {
		r0 = rf(ctx, shopID, userID)
	} else {
		r0 = ret.Get(0).(identity.Membership)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, shopID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMembershipRepository_GetByShopAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByShopAndUser'
type MockMembershipRepository_GetByShopAndUser_Call struct {
	*mock.Call
}

// GetByShopAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID string
//   - userID string
func (_e *MockMembershipRepository_Expecter) GetByShopAndUser(ctx interface{}, shopID interface{}, userID interface{}) *MockMembershipRepository_GetByShopAndUser_Call {
	return &MockMembershipRepository_GetByShopAndUser_Call{Call: _e.mock.On("GetByShopAndUser", ctx, shopID, userID)}
}

func (_c *MockMembershipRepository_GetByShopAndUser_Call) Run(run func(ctx context.Context, shopID string, userID string)) *MockMembershipRepository_GetByShopAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMembershipRepository_GetByShopAndUser_Call) Return(_a0 identity.Membership, _a1 error) *MockMembershipRepository_GetByShopAndUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMembershipRepository_GetByShopAndUser_Call) RunAndReturn(run func(context.Context, string, string) (identity.Membership, error)) *MockMembershipRepository_GetByShopAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListByShop provides a mock function with given fields: ctx, shopID
func (_m *MockMembershipRepository) ListByShop(ctx context.Context, shopID string) ([]identity.Membership, error) {
	ret := _m.Called(ctx, shopID)

	if len(ret) == 0 {
		panic("no return value specified for ListByShop")
	}

	var r0 []identity.Membership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]identity.Membership, error)); ok {
		return rf(ctx, shopID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []identity.Membership); ok {
		r0 = rf(ctx, shopID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]identity.Membership)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shopID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMembershipRepository_ListByShop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByShop'
type MockMembershipRepository_ListByShop_Call struct {
	*mock.Call
}

// ListByShop is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID string
func (_e *MockMembershipRepository_Expecter) ListByShop(ctx interface{}, shopID interface{}) *MockMembershipRepository_ListByShop_Call {
	return &MockMembershipRepository_ListByShop_Call{Call: _e.mock.On("ListByShop", ctx, shopID)}
}

func (_c *MockMembershipRepository_ListByShop_Call) Run(run func(ctx context.Context, shopID string)) *MockMembershipRepository_ListByShop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMembershipRepository_ListByShop_Call) Return(_a0 []identity.Membership, _a1 error) *MockMembershipRepository_ListByShop_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMembershipRepository_ListByShop_Call) RunAndReturn(run func(context.Context, string) ([]identity.Membership, error)) *MockMembershipRepository_ListByShop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMembershipRepository creates a new instance of MockMembershipRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMembershipRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMembershipRepository {
	mock := &MockMembershipRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
