// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	identity "github.com/gcollin65/barbershop/internal/identity"
	mock "github.com/stretchr/testify/mock"
)

// MockShopManager is an autogenerated mock type for the ShopManager type
type MockShopManager struct {
	mock.Mock
}

type MockShopManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShopManager) EXPECT() *MockShopManager_Expecter {
	return &MockShopManager_Expecter{mock: &_m.Mock}
}

// GetShop provides a mock function with given fields: ctx, shopID
func (_m *MockShopManager) GetShop(ctx context.Context, shopID string) (identity.Shop, error) {
	ret := _m.Called(ctx, shopID)

	if len(ret) == 0 {
		panic("no return value specified for GetShop")
	}

	var r0 identity.Shop
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (identity.Shop, error)); ok {
		return rf(ctx, shopID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) identity.Shop); ok {
		r0 = rf(ctx, shopID)
	} else {
		r0 = ret.Get(0).(identity.Shop)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shopID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockShopManager_GetShop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShop'
type MockShopManager_GetShop_Call struct {
	*mock.Call
}

// GetShop is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID string
func (_e *MockShopManager_Expecter) GetShop(ctx interface{}, shopID interface{}) *MockShopManager_GetShop_Call {
	return &MockShopManager_GetShop_Call{Call: _e.mock.On("GetShop", ctx, shopID)}
}

func (_c *MockShopManager_GetShop_Call) Run(run func(ctx context.Context, shopID string)) *MockShopManager_GetShop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockShopManager_GetShop_Call) Return(_a0 identity.Shop, _a1 error) *MockShopManager_GetShop_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockShopManager_GetShop_Call) RunAndReturn(run func(context.Context, string) (identity.Shop, error)) *MockShopManager_GetShop_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateShop provides a mock function with given fields: ctx, shopID, input
func (_m *MockShopManager) UpdateShop(ctx context.Context, shopID string, input identity.ShopUpdateInput) (identity.Shop, error) {
	ret := _m.Called(ctx, shopID, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateShop")
	}

	var r0 identity.Shop
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, identity.ShopUpdateInput) (identity.Shop, error)); ok {
		return rf(ctx, shopID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, identity.ShopUpdateInput) identity.Shop); ok {
		r0 = rf(ctx, shopID, input)
	} else {
		r0 = ret.Get(0).(identity.Shop)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, identity.ShopUpdateInput) error); ok {
		r1 = rf(ctx, shopID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockShopManager_UpdateShop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateShop'
type MockShopManager_UpdateShop_Call struct {
	*mock.Call
}

// UpdateShop is a helper method to define mock.On call
//   - ctx context.Context
//   - shopID string
//   - input identity.ShopUpdateInput
func (_e *MockShopManager_Expecter) UpdateShop(ctx interface{}, shopID interface{}, input interface{}) *MockShopManager_UpdateShop_Call {
	return &MockShopManager_UpdateShop_Call{Call: _e.mock.On("UpdateShop", ctx, shopID, input)}
}

func (_c *MockShopManager_UpdateShop_Call) Run(run func(ctx context.Context, shopID string, input identity.ShopUpdateInput)) *MockShopManager_UpdateShop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(identity.ShopUpdateInput))
	})
	return _c
}

func (_c *MockShopManager_UpdateShop_Call) Return(_a0 identity.Shop, _a1 error) *MockShopManager_UpdateShop_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockShopManager_UpdateShop_Call) RunAndReturn(run func(context.Context, string, identity.ShopUpdateInput) (identity.Shop, error)) *MockShopManager_UpdateShop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockShopManager creates a new instance of MockShopManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShopManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShopManager {
	mock := &MockShopManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
