// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	identity "github.com/gcollin65/barbershop/internal/identity"
	mock "github.com/stretchr/testify/mock"
)

// MockSigner is an autogenerated mock type for the Signer type
type MockSigner struct {
	mock.Mock
}

type MockSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSigner) EXPECT() *MockSigner_Expecter {
	return &MockSigner_Expecter{mock: &_m.Mock}
}

// SignUp provides a mock function with given fields: ctx, req
func (_m *MockSigner) SignUp(ctx context.Context, req identity.SignUpRequest) (identity.SignUpResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 identity.SignUpResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identity.SignUpRequest) (identity.SignUpResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identity.SignUpRequest) identity.SignUpResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(identity.SignUpResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, identity.SignUpRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSigner_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockSigner_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - req identity.SignUpRequest
func (_e *MockSigner_Expecter) SignUp(ctx interface{}, req interface{}) *MockSigner_SignUp_Call {
	return &MockSigner_SignUp_Call{Call: _e.mock.On("SignUp", ctx, req)}
}

func (_c *MockSigner_SignUp_Call) Run(run func(ctx context.Context, req identity.SignUpRequest)) *MockSigner_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identity.SignUpRequest))
	})
	return _c
}

func (_c *MockSigner_SignUp_Call) Return(_a0 identity.SignUpResponse, _a1 error) *MockSigner_SignUp_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSigner_SignUp_Call) RunAndReturn(run func(context.Context, identity.SignUpRequest) (identity.SignUpResponse, error)) *MockSigner_SignUp_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSigner creates a new instance of MockSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSigner {
	mock := &MockSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
