// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	identity "github.com/gcollin65/barbershop/internal/identity"
	mock "github.com/stretchr/testify/mock"
)

// MockShopRepository is an autogenerated mock type for the ShopRepository type
type MockShopRepository struct {
	mock.Mock
}

type MockShopRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShopRepository) EXPECT() *MockShopRepository_Expecter {
	return &MockShopRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, shop
func (_m *MockShopRepository) Create(ctx context.Context, shop identity.Shop) (identity.Shop, error) {
	ret := _m.Called(ctx, shop)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 identity.Shop
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identity.Shop) (identity.Shop, error)); ok {
		return rf(ctx, shop)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identity.Shop) identity.Shop); ok {
		r0 = rf(ctx, shop)
	} else {
		r0 = ret.Get(0).(identity.Shop)
	}

	if rf, ok := ret.Get(1).(func(context.Context, identity.Shop) error); ok {
		r1 = rf(ctx, shop)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockShopRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockShopRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - shop identity.Shop
func (_e *MockShopRepository_Expecter) Create(ctx interface{}, shop interface{}) *MockShopRepository_Create_Call {
	return &MockShopRepository_Create_Call{Call: _e.mock.On("Create", ctx, shop)}
}

func (_c *MockShopRepository_Create_Call) Run(run func(ctx context.Context, shop identity.Shop)) *MockShopRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identity.Shop))
	})
	return _c
}

func (_c *MockShopRepository_Create_Call) Return(_a0 identity.Shop, _a1 error) *MockShopRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockShopRepository_Create_Call) RunAndReturn(run func(context.Context, identity.Shop) (identity.Shop, error)) *MockShopRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockShopRepository) GetByID(ctx context.Context, id string) (identity.Shop, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 identity.Shop
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (identity.Shop, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) identity.Shop); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(identity.Shop)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockShopRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockShopRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockShopRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockShopRepository_GetByID_Call {
	return &MockShopRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockShopRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockShopRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockShopRepository_GetByID_Call) Return(_a0 identity.Shop, _a1 error) *MockShopRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockShopRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (identity.Shop, error)) *MockShopRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySlug provides a mock function with given fields: ctx, slug
func (_m *MockShopRepository) GetBySlug(ctx context.Context, slug string) (identity.Shop, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 identity.Shop
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (identity.Shop, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) identity.Shop); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Get(0).(identity.Shop)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockShopRepository_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type MockShopRepository_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockShopRepository_Expecter) GetBySlug(ctx interface{}, slug interface{}) *MockShopRepository_GetBySlug_Call {
	return &MockShopRepository_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *MockShopRepository_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockShopRepository_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockShopRepository_GetBySlug_Call) Return(_a0 identity.Shop, _a1 error) *MockShopRepository_GetBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockShopRepository_GetBySlug_Call) RunAndReturn(run func(context.Context, string) (identity.Shop, error)) *MockShopRepository_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, shop
func (_m *MockShopRepository) Update(ctx context.Context, shop identity.Shop) (identity.Shop, error) {
	ret := _m.Called(ctx, shop)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 identity.Shop
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identity.Shop) (identity.Shop, error)); ok {
		return rf(ctx, shop)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identity.Shop) identity.Shop); ok {
		r0 = rf(ctx, shop)
	} else {
		r0 = ret.Get(0).(identity.Shop)
	}

	if rf, ok := ret.Get(1).(func(context.Context, identity.Shop) error); ok {
		r1 = rf(ctx, shop)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockShopRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockShopRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - shop identity.Shop
func (_e *MockShopRepository_Expecter) Update(ctx interface{}, shop interface{}) *MockShopRepository_Update_Call {
	return &MockShopRepository_Update_Call{Call: _e.mock.On("Update", ctx, shop)}
}

func (_c *MockShopRepository_Update_Call) Run(run func(ctx context.Context, shop identity.Shop)) *MockShopRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identity.Shop))
	})
	return _c
}

func (_c *MockShopRepository_Update_Call) Return(_a0 identity.Shop, _a1 error) *MockShopRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockShopRepository_Update_Call) RunAndReturn(run func(context.Context, identity.Shop) (identity.Shop, error)) *MockShopRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockShopRepository creates a new instance of MockShopRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShopRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShopRepository {
	mock := &MockShopRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
